name: 'macports-ci'
description: 'Install MacPorts'
inputs:
  prefix:
    description: 'install to this prefix'
    required: true
    default: ''
  mode:
    description: 'binary or source'
    required: true
    default: 'binary'
  ports:
    description: 'install these ports'
    required: true
    default: ''
  localports:
    description: 'location of local ports'
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - run:
        ${{ github.action_path }}/run.sh
        prefix="${{ inputs.prefix }}"
        mode="${{ inputs.mode }}"
        ports="${{ inputs.ports }}"
        localports="${{ inputs.localports }}"
      shell: bash
