name: 'macports-ci'
description: 'Install MacPorts'
inputs:
  prefix:
    description: 'install to this prefix'
    required: true
    default: ''
  mode:
    description: 'binary or source'
    required: true
    default: 'binary'
  localports:
    description: 'location of local ports'
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/run.sh ${{ inputs.prefix }} ${{ inputs.mode }}
      shell: bash
