name: 'macports-ci'
description: 'Install MacPorts'
inputs:
  prefix:
    description: 'install to this prefix'
    required: true
    default: ''
  source:
    description: 'set to true to force install from source'
    required: true
    default: ''
  localports:
    description: 'location of local ports'
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/run.sh ${{ inputs.prefix }}
      shell: bash
