on: [push]

jobs:
  test:
    runs-on: macos-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - uses: GiovanniBussi/macports-ci-action@master
      with:
        ports: xdrfile python38
    - name: Install a package
      run: |
        which trr2xtc
        python3.8 --version
  prefix:
    runs-on: macos-latest
    name: Prefix
    steps:
    - uses: actions/checkout@v2
    - uses: GiovanniBussi/macports-ci-action@master
      with:
        prefix: '/opt/alt-prefix/'
    - name: Install a package
      run: |
        sudo port install xdrfile
  source:
    runs-on: macos-latest
    name: Source
    steps:
    - uses: actions/checkout@v2
    - uses: GiovanniBussi/macports-ci-action@master
      with:
        mode: source
    - name: Install a package
      run: |
        sudo port install xdrfile
